//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by POP.rc
//
#define IDOK2                           2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDR_MAINFRAME                   101
#define IDD_DLG_LOGIN                   102
#define IDD_DLG_INCOMING_CALL           103
#define IDD_DLG_SETTING                 104
#define IDD_DLG_ALERTING_CALL           105
#define IDD_DLG_DIALOG                  106
#define IDD_DLG_CHATINPUT               107
#define IDD_DLG_CHATRIGHT               108
#define IDD_DLG_TRANFILE                109
#define IDD_PAN_FILES                   110
#define IDD_EBDIALOGBASE                111
#define IDD_DLG_USERLIST                112
#define IDD_DLG_CALL_NUMBER             113
#define IDD_DLG_DIARECORD               113
#define IDD_DLG_MY_CONTACTS             114
#define IDD_DLG_NUMBERS                 115
#define IDD_DLG_CONTACT_INFO            116
#define IDD_DLG_MY_ENTERPRISE           117
#define IDD_DLG_ENTERPRISE_INFO         118
#define IDD_DLG_GROUP_INFO              119
#define IDD_DLG_MEMBER_INFO             120
#define IDD_DLG_MY_GROUP                121
#define IDD_DLG_USERINFO                122
#define IDD_DLG_SEL_USER                123
#define IDD_DLG_EDIT_EMPINFO            124
#define IDD_DLG_EDIT_ACCINFO            125
#define IDD_DLG_EDIT_EMPLIST            126
#define IDD_DLG_MGR_MYINFO              127
#define IDD_DLG_REG                     128
#define IDB_BITMAP_BTN_FONT             129
#define IDD_DLG_MY_SESSION              129
#define IDB_BITMAP_BTN_FILE             130
#define IDD_DLG_EDIT_PASSWD             130
#define IDB_BITMAP_PROGRESS             131
#define IDD_DLG_EDIT_INFO               131
#define IDB_BITMAP_TAB_CHATRIGHT        132
#define IDD_POP_CONTACTINFO             132
#define IDD_DLG_VIEW_CONTACTINFO        132
#define IDD_DLG_MESSAGE_BOX             133
#define IDB_BITMAP1                     134
#define IDB_BITMAP_BTN_6821             134
#define IDD_PAN_VIDEOS                  134
#define IDB_BITMAP_BTN_11629            135
#define IDD_DLG_EDIT_ACCSETTING         135
#define IDB_BITMAP_BTN_4821             136
#define IDD_PAN_MSG_RECORD              136
#define IDB_BITMAP_BTN_7024             137
#define IDB_PNG1                        139
#define IDB_PNG_BTN                     140
#define IDB_TREE_CLOSED                 146
#define IDB_TREE_OPENED                 147
#define IDI_ICON5                       153
#define IDD_POP_DIALOG                  156
#define IDD_DLG_DIALOG1                 157
#define IDD_DLG_MSGRECORD               157
#define IDD_DLG_MSGRECORD1              158
#define IDD_DLG_FILE_MANAGER            158
#define IDD_DLG_EDIT_PASSWD1            159
#define IDD_DLG_EDIT_VIDEO              159
#define IDD_DLG_VOICEBAR                160
#define IDD_DLG_VOICE                   161
#define IDD_DLG_VIDEO                   161
#define IDB_BITMAP7                     162
#define IDD_DLG_CHANGE_HEAD             162
#define IDD_DLG_VIDEO_PHOTO             163
#define IDD_DLG_RESOURCEMGR             164
#define IDD_DLG_EMOTION_SELECT          165
#define IDB_PNG_BTN_LOGIN               166
#define IDD_DLG_LOGIN1                  166
#define IDD_DLG_OAUTH                   166
#define IDD_DLG_CHATRIGHT1              167
#define IDD_DLG_SELECT_HEAD             167
#define IDB_PNG_TAB_CONTACT             168
#define IDD_DLG_FUNC_WINDOW             168
#define IDB_PNG_TAB_DEP                 169
#define IDD_DLG_CONTACT_INFO1           169
#define IDD_DLG_VIDEO_CONFERENCE        169
#define IDB_PNG_TAB_ENT                 170
#define IDD_DLG_VIDEOCONTROL            170
#define IDB_PNG5                        171
#define IDB_PNG_TAB_SES                 171
#define IDB_PNG_TAB_56X24               174
#define IDB_PNG_BTN_STATE_AWAY          175
#define IDB_PNG_BTN_STATE_BUSY          176
#define IDB_PNG4                        177
#define IDB_PNG_BTN_STATE_ONLINE        177
#define IDB_PNG_HOT_CALL                178
#define IDB_PNG_HOT_DELETE              179
#define IDB_PNG_HOT_EDIT                180
#define IDB_PNG_HOT_NEW                 181
#define IDB_PNG_BTN_EMOTION             182
#define IDB_PNG2                        183
#define IDB_PNG_BTN_EBCS                183
#define IDB_PNG_BTN_SENDFILE            187
#define IDB_PNG_BTN_ADDUSER             188
#define IDB_PNG_BTN_AUDIOCHAT           189
#define IDB_PNG_BTN_VIDEOCHAT           190
#define IDB_PNG_BTN_GROUPRES            191
#define IDB_PNG_BTN_GROUPSHARE          191
#define IDI_ICON1                       192
#define IDB_PNG_BTN_HANGUPCALL          193
#define IDB_PNG_BTN_EXITCHAT            193
#define IDB_BITMAP2                     200
#define IDB_PNG_IMG_QUESTION            204
#define IDB_PNG_IMG_WARNING             205
#define IDB_PNG_IMG_TIP                 206
#define IDB_PNG_IMG_ERROR               207
#define IDB_PNG_CHECKBOX                209
#define IDB_PNG_71X32G                  210
#define IDB_PNG3                        211
#define IDB_PNG_68X27G                  211
#define IDB_PNG6                        212
#define IDB_PNG_BTN_MSGRECORD           212
#define IDB_PNG_TAB_ACCINFO             213
#define IDB_PNG_TAB_ACCSETTING          214
#define IDB_PNG9                        215
#define IDB_PNG_TAB_SETPWD              215
#define IDB_PNG_TAB_SETVIDEO            216
#define IDB_PNG_TAB_SELCONTACT          217
#define IDB_PNG_TAB_SELGROUP            218
#define IDB_PNG_TAB_SELORG              219
#define IDB_PNG_BTN_SELIMG              220
#define IDB_PNG_BTN_SELMYVIDEO          221
#define IDB_PNG_TAB_86X69               222
#define IDB_PNG_HOT_CALLS               223
#define IDB_PNG_HOT_DELETES             224
#define IDB_PNG_BTN_HOTDOWN             225
#define IDB_PNG_HOT_EDITS               226
#define IDB_PNG_HOT_NEWS                227
#define IDB_PNG_HOT_OPENDIR             228
#define IDB_PNG_HOT_OPENFILE            229
#define IDB_PNG7                        230
#define IDB_PNG_TAB_86X49               230
#define IDB_PNG8                        231
#define IDB_PNG_IMG1_CLOUD              231
#define IDB_PNG_IMG1_GROUP              232
#define IDB_PNG_IMG1_PEOPLE             233
#define IDB_PNG10                       234
#define IDB_PNG_IMG2_CLOUD              234
#define IDB_PNG11                       235
#define IDB_PNG_IMG1_ORG                235
#define IDB_PNG_DEFAULT_DEPARTMENT      237
#define IDB_PNG_DEFAULT_GROUP           238
#define IDB_PNG_DEFAULT_PROJECT         240
#define IDB_PNG_DEFAULT_TEMPGROUP       241
#define IDB_PNG_STATE_AWAY              242
#define IDB_PNG_STATE_BUSY              243
#define IDB_PNG_DEFAULT_ORG             244
#define IDB_PNG12                       245
#define IDB_PNG_DEFAULT_VISITOR         245
#define IDB_PNG_BTN_FILE_MGR            246
#define IDB_PNG_BTN_MY_CENTER           247
#define IDB_PNG_BTN_MY_SHARE            248
#define IDB_PNG_BTN_MAIN_FUNC           249
#define IDB_PNG_BTN_CHAT_FUNC           250
#define IDB_VIDEOCONTROL_BG             250
#define IDB_PNG_VC_SPEEK                251
#define IDB_PNG14                       252
#define IDB_PNG_VC_VIDEO                252
#define IDD_DIALOG1                     253
#define IDD_DLG_SHRINKAGEBAR            253
#define IDB_PNG13                       254
#define IDB_PNG_BTN_REMOTEDESKTOP       254
#define IDD_PAN_RD                      254
#define IDD_DLG_VIDEO1                  255
#define IDD_DLG_REMOTE_DESKTOP          255
#define IDB_PNG_BTN_REFRESH72X18        255
#define IDD_DLG_RD_WINDOW               256
#define IDD_DLG_RD_WINDOWS              256
#define IDB_PNG_BTN_GOBACK72X18         256
#define IDD_DLG_FRAME                   257
#define IDD_DLG_FRAMELIST               257
#define IDB_PNG_BTN_GOFORWARD72X18      257
#define IDD_DLG_APPFRAME                258
#define IDB_PNG_BTN_ARROWDOWN72X18      258
#define IDD_DLG_APPFRAME1               259
#define IDD_DLG_APPWINDOW               259
#define IDB_PNG15                       259
#define IDB_PNG_REDCIR_16X16            259
#define IDD_PAN_RD1                     260
#define IDD_PAN_SEARCH                  260
#define IDB_PNG_WORKFRAME               260
#define IDD_PAN_BROWSER_NAVIGATE        261
#define IDB_PNG17                       261
#define IDB_PNG_MAINFRAME               261
#define IDD_DLG_MSG_TIP                 262
#define IDB_TREE_TYPE0_CLOSED           262
#define IDD_DLG_MSGRECORD2              263
#define IDD_DLG_MSGRECORD_CHILD         263
#define IDB_TREE_TYPE0_OPENED           263
#define IDD_DLG_RESOURCEMGR1            264
#define IDD_DLG_RESOURCEMGR_CHILD       264
#define IDB_TREE_TYPE1_CLOSED           264
#define IDB_TREE_TYPE1_OPENED           265
#define IDD_DLG_TOOLBAR                 265
#define IDB_TREE_TYPE2_CLOSED           266
#define IDD_PAN_FIND                    266
#define IDB_TREE_TYPE2_OPENED           267
#define IDD_PAN_FIND1                   267
#define IDD_PAN_TEXT                    267
#define IDB_BITMAP8                     268
#define IDB_TREE_TYPE9_CLOSED           268
#define IDD_DLG_PROMPT                  268
#define IDB_TREE_TYPE9_OPENED           269
#define IDD_PAN_SEARCH1                 269
#define IDD_PAN_SEARCH_RESULT           269
#define IDI_ICON_BROWSER_CHROME         270
#define IDD_DLG_MEMBER_INFO1            270
#define IDD_DLG_REQUEST_ADD_CONTACT     270
#define IDI_ICON_BROWSER_IE             271
#define IDB_BITMAP_BROWSER_CHROME       272
#define IDB_BITMAP_BROWSER_IE           273
#define IDB_BITMAP3                     274
#define IDB_BITMAP_SELECT_COLOR         274
#define IDB_BITMAP_MENU_ONLINE          275
#define IDB_BITMAP_MENU_AWAY            276
#define IDB_BITMAP5                     277
#define IDB_BITMAP_MENU_BUSY            277
#define IDB_BITMAP_MENU_CALL            279
#define IDB_BITMAP_MENU_ADD             280
#define IDB_BITMAP_MENU_EDIT            281
#define IDB_BITMAP4                     284
#define IDB_BITMAP_MENU_TOOLBAR         285
#define IDB_BITMAP6                     287
#define IDB_BITMAP_MENU_ADDUSER         288
#define IDB_BITMAP_MENU_MSG             289
#define IDB_BITMAP_MENU_SHARE           290
#define IDB_BITMAP_MENU_UPLOAD          291
#define IDB_BITMAP10                    292
#define IDB_BITMAP_MENU_DELSHARE        292
#define IDB_PNG_BTN_MY_SHARE_UISTYLE1   294
#define IDB_PNG_BTN_MY_CENTER_UISTYLE1  295
#define IDB_PNG_BTN_FILE_MGR_UISTYLE    297
#define IDB_PNG_BTN_FILE_MGR_UISTYLE1   297
#define IDB_PNG_ENTBOOST42              299
#define IDB_PNG_BTN_SEND_ECARD          300
#define IDB_PNG_STATE_FORBID            301
#define IDB_BITMAP_FORBID_SPEECH        302
#define IDC_BUTTON_CALLUSER             1001
#define IDC_STATIC_SAVEPWD              1001
#define IDC_STATIC_LINE_CONVERSATION    1001
#define IDC_EDIT_CALLEE                 1002
#define IDC_BUTTON_LINESTATE            1002
#define IDC_BUTTON_SELECTUSER           1003
#define IDC_BUTTON_MY_CENTER            1003
#define IDC_BUTTON_SELECTUSER2          1004
#define IDC_COMBO_USERS                 1004
#define IDC_BUTTON_MY_SHARE             1004
#define IDC_BUTTON_SELECTUSER3          1005
#define IDC_EDIT_PASSWORD               1005
#define IDC_BUTTON_MY_SHARE2            1005
#define IDC_BUTTON_FILE_MGR             1005
#define IDC_BUTTON_LOGOUT               1006
#define IDC_CHECK_SAVEPWD               1006
#define IDC_EDIT_PWD_CONFIRM            1006
#define IDC_BUTTON_MY_SHARE3            1006
#define IDC_BUTTON_MY_FUNC              1006
#define IDC_BUTTON_MAIN_FUNC            1006
#define IDC_STATIC_ERROR                1006
#define IDC_STATIC_STATUS_TEXT          1006
#define IDC_STATIC_NOTIFY1              1006
#define IDC_CHECK_SAVEPWD2              1007
#define IDC_CHECK_AUTOLOGIN             1007
#define IDC_BUTTON_REGISTER             1008
#define IDC_BUTTON_LOGIN                1009
#define IDC_BUTTON_VISITOR              1010
#define IDC_BUTTON_ACCEPT               1011
#define IDC_BUTTON_SETTING              1011
#define IDC_BUTTON_REJECT               1012
#define IDC_BUTTON_REG                  1012
#define IDC_BUTTON_DELALL               1012
#define IDC_EDIT_SERVER                 1013
#define IDC_BUTTON_CANCEL               1013
#define IDC_BUTTON_DELALL2              1013
#define IDC_BUTTON_VIEWALL              1013
#define IDC_BUTTON_HANGUP               1014
#define IDC_BUTTON_CANCEL2              1014
#define IDC_BUTTON_OFFFILE              1014
#define IDC_BUTTON_SEND                 1016
#define IDC_BUTTON_SEND2                1017
#define IDC_BUTTON_SWITCH_RETURN        1017
#define IDC_BUTTON_SWITCH_RETURN2       1018
#define IDC_BUTTON_MIN_EBSC             1018
#define IDC_BUTTON_FONT                 1019
#define IDC_BUTTON_FILE                 1020
#define IDC_BUTTON_SAVEAS               1020
#define IDC_BUTTON_MSG_RECORD           1020
#define IDC_STATIC_FILENAME             1021
#define IDC_BUTTON_FILE_MANAGER         1021
#define IDC_BUTTON_FILE2                1021
#define IDC_BUTTON_AUDIO                1021
#define IDC_BUTTON_SAVE                 1022
#define IDC_PROGRESS_PERCENT            1023
#define IDC_BUTTON_FILE_MANAGER2        1023
#define IDC_BUTTON_EBSC                 1023
#define IDC_STATIC_SHEECHSTATUS         1024
#define IDC_BUTTON_ADD_USER             1024
#define IDC_BUTTON_EBSC2                1024
#define IDC_BUTTON_IMAGE                1024
#define IDC_LIST_USERS                  1025
#define IDC_BUTTON_SEND_FILE            1025
#define IDC_BUTTON_SAVEAS2              1025
#define IDC_BUTTON_SAVE2CLOUDDRIVE      1025
#define IDC_BUTTON_IMAGE2               1025
#define IDC_STATIC_USERS                1026
#define IDC_BUTTON_EXIT_CHAT            1026
#define IDC_STATIC_FILES                1027
#define IDC_EDIT_NUMBER                 1027
#define IDC_BUTTON_SEND_FILE2           1027
#define IDC_BUTTON_VIDEO                1027
#define IDC_STATIC_USERS2               1028
#define IDC_STATIC_ECARD                1028
#define IDC_BUTTON_GROUP_SHARE          1028
#define IDC_LIST1                       1029
#define IDC_LIST_NUMBERS                1029
#define IDC_STATIC_VIDEOS               1029
#define IDC_BUTTON_FUNC                 1029
#define IDC_BUTTON_CHAT_FUNC            1029
#define IDC_COMBO_NUMBERS               1030
#define IDC_STATIC_MSG_RECORD           1030
#define IDC_BUTTON_RD                   1030
#define IDC_TREE_CONTACTS               1031
#define IDC_STATIC_CONTACTS             1032
#define IDC_STATIC_ENTERPRISE           1033
#define IDC_STATIC_DEPARTMENT           1034
#define IDC_COMBO_GROUP                 1035
#define IDC_STATIC_ADDRESS              1036
#define IDC_EDIT_CONTACT_NAME           1037
#define IDC_TREE_ENTERPRISE             1037
#define IDC_EDIT_CONTACT_PHONE          1038
#define IDC_TREE_CONTACT                1038
#define IDC_EDIT_CONTACT_EMAIL          1039
#define IDC_TREE_SELECTED               1039
#define IDC_TREE_SEARCH_RESULT          1040
#define IDC_TREE_SEARCH                 1040
#define IDC_EDIT_CONTACT_DESCRIPTION    1041
#define IDC_EDIT_CONTACT                1041
#define IDC_COMBO_CONTACT               1042
#define IDC_EDIT_ENT_NAME               1042
#define IDC_EDIT_FAX                    1043
#define IDC_EDIT_COMPANY                1043
#define IDC_EDIT_PHONE                  1044
#define IDC_EDIT_FAX2                   1044
#define IDC_EDIT_TEL                    1045
#define IDC_EDIT_ADDRESS                1046
#define IDC_EDIT_DESCRIPTION            1047
#define IDC_EDIT_TEL3                   1047
#define IDC_EDIT_JOBTITLE               1047
#define IDC_EDIT_URL                    1048
#define IDC_EDIT_JOB_TITLE              1048
#define IDC_EDIT_DEPARTMENT             1048
#define IDC_EDIT_ZIPCODE                1048
#define IDC_EDIT_DEP_NAME               1049
#define IDC_EDIT_JOB_POSITION           1049
#define IDC_EDIT_DEPARTMENT2            1049
#define IDC_EDIT_ENTERPRISE             1049
#define IDC_EDIT_JOB_TITLE2             1049
#define IDC_EDIT_USERNAME               1050
#define IDC_EDIT_URL2                   1050
#define IDC_EDIT_DISPLAY_INDEX          1050
#define IDC_EDIT_EMP_ACCOUNT            1051
#define IDC_EDIT_DEPNAME                1051
#define IDC_EDIT_WORK_PHONE             1052
#define IDC_EDIT_CELL_PHONE             1053
#define IDC_EDIT_HOME_NUMBER            1054
#define IDC_EDIT_ACCOUNT                1054
#define IDC_EDIT_DEPNAME2               1054
#define IDC_TREE_DEPARTMENT             1055
#define IDC_EDIT_WORK_PHONE2            1055
#define IDC_EDIT_MAINPAGE               1055
#define IDC_BUTTON_CLOSE                1056
#define IDC_BUTTON_MIN                  1057
#define IDC_BUTTON_CLOSE2               1057
#define IDC_BUTTON_DEFAULT_EMP          1057
#define IDC_BUTTON_OPENFILE             1057
#define IDC_BUTTON_PHOTO                1057
#define IDC_BUTTON_ON                   1057
#define IDC_BUTTON_MANAGER_NAME         1057
#define IDC_BUTTON_CONTACT              1058
#define IDC_BUTTON_MAX                  1058
#define IDC_BUTTON_MIN2                 1058
#define IDC_BUTTON_SKIN                 1058
#define IDC_BUTTON_MY_VIDEO             1058
#define IDC_BUTTON_CHANGEHEAD           1058
#define IDC_BUTTON_OFF                  1058
#define IDC_BUTTON_ENTERPRISE           1059
#define IDC_BUTTON_CALL                 1059
#define IDC_BUTTON_CALL_TRACK           1059
#define IDC_BUTTON_HEAD1                1059
#define IDC_BUTTON_OFF2                 1059
#define IDC_BUTTON_EXIT                 1059
#define IDC_BUTTON_DEPARTMENT           1060
#define IDC_EDIT_NAME                   1060
#define IDC_BUTTON_CONTACT3             1060
#define IDC_BUTTON_HEAD2                1060
#define IDC_EDIT_SEARCH                 1061
#define IDC_STATIC_NAME                 1061
#define IDC_EDIT_EMAIL                  1062
#define IDC_BUTTON_CONTACT2             1062
#define IDC_BUTTON_SESSION              1062
#define IDC_STATIC_AREA                 1062
#define IDC_STATIC_TEL                  1063
#define IDC_BUTTON_SKIN2                1063
#define IDC_EDIT_EMAIL2                 1063
#define IDC_STATIC_EMAIL                1064
#define IDC_BUTTON_MAX2                 1064
#define IDC_STATIC_ZIPCODE              1064
#define IDC_STATIC_JOBTITLE             1065
#define IDC_STATIC_EMAIL2               1065
#define IDC_EDIT_DEP_DESCRIPTION        1066
#define IDC_STATIC_PHONE                1066
#define IDC_STATIC_ACCOUNT              1067
#define IDC_COMBO_GENDER                1068
#define IDC_EDIT_NAME2                  1068
#define IDC_COMBO_BIR_YEAR              1069
#define IDC_COMBO_BIR_MONTH             1070
#define IDC_COMBO_BIR_DAY               1071
#define IDC_TREE_EMPLIST                1072
#define IDC_EDIT1                       1073
#define IDC_EDIT_FINDTEXT               1073
#define IDC_TREE_SESSION                1074
#define IDC_EDIT_OLDPWD                 1075
#define IDC_BUTTON_ACCINFO              1076
#define IDC_EDIT_NEWPWD                 1077
#define IDC_BUTTON_ACCINFO2             1077
#define IDC_BUTTON_PASSWD               1077
#define IDC_TREE_USERS                  1077
#define IDC_EDIT_CONFIRM                1078
#define IDC_COMBO_SENDTO                1078
#define IDC_BUTTON_ACC_SETTING          1078
#define IDC_BUTTON_ACCSETTING           1078
#define IDC_CHECK1                      1079
#define IDC_CHECK_PRIVATE               1079
#define IDC_CHECK_ENABLE_VISITOR_CALL   1079
#define IDC_CHECK_ENABLE_CONTROL        1079
#define IDC_COMBO_VIDEOS                1080
#define IDC_CHECK_ENABLE_OFF_CALL       1080
#define IDC_BUTTON_LOCAL_VIDEO          1081
#define IDC_CHECK_ENABLE_OFF_FILE       1081
#define IDC_BUTTON_VIDEO_REQUEST        1082
#define IDC_CHECK_ENABLE_VISITOR_ACCEPT 1082
#define IDC_BUTTON_VIDEO_END            1083
#define IDC_CHECK_ENABLE_OUTENT_CALL    1083
#define IDC_STATIC_VIDEO_DESC           1084
#define IDC_CHECK_ENABLE_OFF_CALL2      1084
#define IDC_CHECK_CONNECTED_OPEN_CHAT   1084
#define IDC_CHECK_ENABLE_CONTACT_ACCEPT 1084
#define IDC_CHECK_ENABLE_OUTENT_ACCEPT  1085
#define IDC_BUTTON1                     1085
#define IDC_BUTTON_NULL                 1085
#define IDC_BUTTON_VIDEO_ACCEPT         1086
#define IDC_CHECK_ENABLE_USER_CALL      1086
#define IDC_BUTTON_REFRESH              1086
#define IDC_CHECK_ENABLE_USER_ACCEPT    1087
#define IDC_BUTTON_ECARD                1087
#define IDC_BUTTON_ALLFILE              1087
#define IDC_BUTTON_REFRESH2             1087
#define IDC_BUTTON_DELETEALL            1087
#define IDC_BUTTON_OPTIONS              1087
#define IDC_BUTTON_VIDEO_ACCEPT2        1088
#define IDC_BUTTON_VIDEO_CANCEL         1088
#define IDC_BUTTON_TRANING              1088
#define IDC_BUTTON_ALLNOTE              1088
#define IDC_BUTTON_USERLIST             1088
#define IDC_BUTTON_DELETEALL2           1088
#define IDC_BUTTON_DELETESEARCH         1088
#define IDC_BUTTON_ALL                  1088
#define IDC_BUTTON_REFRESH3             1088
#define IDC_BUTTON_STOP                 1088
#define IDC_BUTTON_VIDEOS               1089
#define IDC_BUTTON_TRANED               1089
#define IDC_BUTTON_ALLFILE2             1089
#define IDC_BUTTON_ALLRES               1089
#define IDC_TREE_TRANED                 1090
#define IDC_BUTTON_ALLNOTE2             1090
#define IDC_BUTTON_ALL_NOTPARENT        1090
#define IDC_BUTTON_VIDEOS2              1090
#define IDC_VOICE_BAR                   1091
#define IDC_BUTTON_NEWDIR               1091
#define IDC_TREE_DIR                    1092
#define IDC_TREE_DIR2                   1093
#define IDC_TREE_ITEM                   1093
#define IDC_BUTTON_NEWFILE              1094
#define IDC_STATIC_SELECTED             1096
#define IDC_STATIC_PRIVATE              1097
#define IDC_BUTTON_FILES                1098
#define IDC_EXPLORER1                   1098
#define IDC_STATIC_VIDEO                1099
#define IDC_STATIC_SPEEK                1100
#define IDC_STATIC_OUTENT               1100
#define IDC_STATIC_REG                  1101
#define IDC_STATIC_VISITOR              1102
#define IDC_STATIC_OFFLINE              1103
#define IDC_COMBO_AREA1                 1104
#define IDC_COMBO_AREA2                 1105
#define IDC_BUTTON_SWITCH_FRAME         1105
#define IDC_COMBO_AREA3                 1106
#define IDC_BUTTON_SWITCH_FRAME2        1106
#define IDC_BUTTON_SWITCH_TOOLBAR       1106
#define IDC_BUTTON_NEW_APP              1106
#define IDC_COMBO_AREA4                 1107
#define IDC_BUTTON_SWITCH_FRAME3        1107
#define IDC_BUTTON_SWITCH_TOOLBAR2      1107
#define IDC_BUTTON_MOVE_FIRST           1107
#define IDC_BUTTON_NEW_APP2             1107
#define IDC_BUTTON_NEW_WEB              1107
#define IDC_BUTTON_MOVE_LAST            1108
#define IDC_BUTTON_SWITCH_FRAME4        1108
#define IDC_BUTTON_NEW_APP3             1108
#define IDC_BUTTON_SWITCH_LEFT          1108
#define IDC_BUTTON_MOVE_PREV            1109
#define IDC_BUTTON_MOVE_LAST2           1110
#define IDC_BUTTON_MOVE_NEXT            1110
#define IDC_DATETIMEPICKER1             1111
#define IDC_BUTTON_GOFORWARD            1112
#define IDC_BUTTON_GOFORWARD2           1113
#define IDC_BUTTON_GOBACK               1113
#define IDC_TREE_MESSAGE                1113
#define IDC_BTN_OPEN_NEW_WINDOW         1114
#define IDC_BTN_2                       1114
#define IDC_BUTTON_GOFORWARD3           1114
#define IDC_BTN_OPEN_NEW_WINDOW2        1115
#define IDC_BTN_OPEN_WINDOW             1115
#define IDC_BTN_1                       1115
#define IDC_STATIC_LABEL1               1115
#define IDC_BTN_3                       1116
#define IDC_BUTTON_UP                   1116
#define IDC_BUTTON_FINDUP               1116
#define IDC_BTN_4                       1117
#define IDC_BUTTON_FINDDOWN             1117
#define IDC_STATIC_RESULT               1118
#define IDC_BTN_5                       1118
#define IDC_BUTTON_SWITCH_RIGHT         1119
#define IDC_BTN_6                       1119
#define IDC_EDIT_USER_INPUT             1120
#define IDC_BTN_7                       1120
#define IDC_BTN_8                       1121
#define IDC_BUTTON_SEND_MSG             1121
#define IDC_BUTTON_SEND_MSG2            1122
#define IDC_BUTTON_REQUEST_ADD_CONTACT  1122
#define IDC_BUTTON_VIEW_MYMSG           1122
#define IDC_EDIT_CONTACT_ADDRESS        1123
#define IDC_EDIT_CONTACT_ACCOUNT        1124
#define IDC_EDIT_DISPLAY_INDEX2         1125
#define IDC_STATIC_GROUP_NAME           6553
#define ID_CONTACT_32771                32771
#define ID_CONTACT_32773                32773
#define ID_CONTACT_32774                32774
#define ID_ENTERPRISE_NEW               32777
#define ID_Menu                         32791
#define ID_CONTACT_IDR                  32792
#define ID_CONTACT_ID                   32793
#define ID_Menu32798                    32798
#define ID_CONTACT_32799                32799
#define IDC_STATIC_DESCRIPTION          32800
#define IDC_STATIC_OLDPWD               32801
#define IDC_STATIC_MANAGER              32801
#define IDC_STATIC_NEWPWD               32802
#define IDC_STATIC_MANAGER2             32802
#define IDC_STATIC_MANAGER_NAME         32802
#define IDC_STATIC_CONFIRM              32803
#define IDC_STATIC_CONTACT              32804
#define IDC_STATIC_GROUP                32805
#define IDC_STATIC_CONTACT_NAME         32806
#define IDC_STATIC_CONTACT_PHONE        32807
#define IDC_STATIC_COMPANY              32808
#define IDC_STATIC_TITLE                32809
#define IDC_STATIC_URL                  32810
#define IDC_STATIC_DISPLAY_INDEX        32811
#define IDC_STATIC_FAX                  32813
#define IDC_STATIC_ENT_NAME             32814
#define IDC_STATIC_USERNAME             32815
#define IDC_STATIC_JOB_TITLE            32816
#define IDC_STATIC_GENDER               32817
#define IDC_STATIC_JOB_POSITION         32818
#define IDC_STATIC_BIRTHDAY             32819
#define IDC_STATIC_WORK_PHONE           32820
#define IDC_STATIC_CELL_PHONE           32821
#define IDC_STATIC_PROMPT               65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        301
#define _APS_NEXT_COMMAND_VALUE         32802
#define _APS_NEXT_CONTROL_VALUE         1123
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
